# Generated by Django 5.0.14 on 2025-06-09 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ferrocarril', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ValidadorDigitoVerificador',
        ),
    ]
