# Generated by Django 5.0.4 on 2025-07-17 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AgenciamientoAduanal', '0013_alter_contactoagenciaaduanal_agencia_aduanal'),
        ('Clientes', '0013_alter_contactoclientepadre_notas'),
        ('Ferrocarril', '0002_delete_validadordigitoverificador'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudMasivaTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('agente_aduanal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitud_masiva_transporte_agente_aduanal', to='AgenciamientoAduanal.agenteaduanal', verbose_name='Agente Aduanal')),
            ],
        ),
        migrations.CreateModel(
            name='SoliciudIndividualTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenedor', models.CharField(max_length=11)),
                ('iniciales_equipo', models.CharField(blank=True, max_length=10, null=True)),
                ('numero_equipo', models.CharField(blank=True, max_length=10, null=True)),
                ('digito_control', models.CharField(blank=True, max_length=1, null=True)),
                ('bl', models.CharField(max_length=16)),
                ('peso_bruto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('longitud_equipo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='longitud del equipo en pies')),
                ('sello_1', models.CharField(blank=True, max_length=20, null=True, verbose_name='Sello 1')),
                ('sello_2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Sello 2')),
                ('sello_3', models.CharField(blank=True, max_length=20, null=True, verbose_name='Sello 3')),
                ('sello_4', models.CharField(blank=True, max_length=20, null=True, verbose_name='Sello 4')),
                ('clave_producto_sat', models.CharField(max_length=20, verbose_name='Clave Producto SAT')),
                ('tipo_material', models.CharField(choices=[('Materia Prima', '01'), ('Materia Procesada', '02'), ('Materia Terminada (Producto terminado)', '03'), ('Materia para la industria manufacturera', '04'), ('Otra', '05')], max_length=50, verbose_name='Tipo de Material')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad')),
                ('descripcion_sat', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('peso_neto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Peso Neto')),
                ('terminal_carga', models.CharField(max_length=100, verbose_name='Terminal de Carga')),
                ('terminal_destino', models.CharField(blank=True, max_length=100, null=True, verbose_name='Terminal de Destino')),
                ('patente', models.CharField(max_length=20, verbose_name='Patente')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('eliminada', models.BooleanField(default=False)),
                ('cliente_padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_individuales_transporte_cliente_padre', to='Clientes.clientepadre', verbose_name='Cliente Padre')),
                ('solicitud_masiva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_individuales_transporte', to='Ferrocarril.solicitudmasivatransporte', verbose_name='Solicitud Masiva')),
            ],
        ),
    ]
