# Generated by Django 5.0.4 on 2025-07-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ferrocarril', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soliciudindividualtransporte',
            name='tipo_material',
            field=models.CharField(choices=[('01', 'Materia Prima'), ('02', 'Materia Procesada'), ('03', 'Materia Terminada (Producto terminado)'), ('04', 'Materia para la industria manufacturera'), ('05', 'Otra')], max_length=50, verbose_name='Tipo de Material'),
        ),
    ]
