# Generated by Django 5.0.14 on 2025-06-04 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ValidadorDigitoVerificador',
        ),
    ]
