# Generated by Django 5.0.4 on 2025-07-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Core', '0002_delete_validadordigitoverificador'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegimenFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(default=1, verbose_name='Código')),
                ('descripcion', models.CharField(default='Por definir', max_length=255, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='UsoCFDI',
            fields=[
                ('codigo', models.CharField(default=1, max_length=10, primary_key=True, serialize=False, verbose_name='Código')),
                ('descripcion', models.TextField(default=1, verbose_name='Descripción')),
            ],
        ),
    ]
