# Generated by Django 5.0.4 on 2025-07-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regimenfiscal',
            name='codigo',
            field=models.IntegerField(verbose_name='Código'),
        ),
    ]
