# Generated by Django 5.0.4 on 2025-07-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clientes', '0006_alter_clientepadre_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgenteAduanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfc', models.CharField(max_length=20, unique=True, verbose_name='RFC')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Correo Electrónico')),
                ('cliente_padre', models.ManyToManyField(to='Clientes.clientepadre', verbose_name='Cliente Padre')),
            ],
        ),
    ]
