# Generated by Django 5.0.4 on 2025-07-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgenciamientoAduanal', '0001_initial'),
        ('Clientes', '0006_alter_clientepadre_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenteaduanal',
            name='cliente_padre',
        ),
        migrations.CreateModel(
            name='AgenciaAduanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de la Agencia Aduanal')),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Correo Electrónico')),
                ('cliente_padre', models.ManyToManyField(related_name='agencias_aduanales', to='Clientes.clientepadre', verbose_name='Cliente Padre')),
            ],
        ),
    ]
