# Generated by Django 5.0.4 on 2025-07-07 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgenciamientoAduanal', '0003_agenciaaduanal_user_agenteaduanal_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenteaduanal',
            name='rfc',
        ),
        migrations.AddField(
            model_name='agenteaduanal',
            name='agencia_aduanal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='agentes_aduanales', to='AgenciamientoAduanal.agenciaaduanal', verbose_name='Agencia Aduanal'),
            preserve_default=False,
        ),
    ]
