# Generated by Django 5.0.4 on 2025-07-09 16:59

import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgenciamientoAduanal', '0004_remove_agenteaduanal_rfc_and_more'),
        ('Core', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenteaduanal',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='agenteaduanal',
            name='nombre',
        ),
        migrations.AddField(
            model_name='agenteaduanal',
            name='calle',
            field=models.CharField(default='Sin especificar', max_length=255, verbose_name='Calle'),
        ),
        migrations.AddField(
            model_name='agenteaduanal',
            name='ciudad',
            field=models.CharField(default='Sin especificar', max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='agenteaduanal',
            name='codigo_postal',
            field=models.IntegerField(default=0, verbose_name='Código Postal'),
        ),
        migrations.AddField(
            model_name='agenteaduanal',
            name='colonia',
            field=models.CharField(default='Sin especificar', max_length=100, verbose_name='Colonia'),
        ),
        migrations.AddField(
            model_name='agenteaduanal',
            name='estado',
            field=models.CharField(default='Sin especificar', max_length=100, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='agenteaduanal',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación'),
        ),
        migrations.AddField(
            model_name='agenteaduanal',
            name='localidad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Localidad'),
        ),
        migrations.AddField(
            model_name='agenteaduanal',
            name='numero_exterior',
            field=models.IntegerField(default=0, verbose_name='Número Exterior'),
        ),
        migrations.AddField(
            model_name='agenteaduanal',
            name='numero_interior',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número Interior'),
        ),
        migrations.AddField(
            model_name='agenteaduanal',
            name='pais',
            field=django_countries.fields.CountryField(default='Sin especificar', max_length=2),
        ),
        migrations.AddField(
            model_name='agenteaduanal',
            name='razon_social',
            field=models.CharField(default='Por definir', max_length=255, verbose_name='Razón Social'),
        ),
        migrations.AddField(
            model_name='agenteaduanal',
            name='referencia',
            field=models.TextField(blank=True, null=True, verbose_name='Referencia'),
        ),
        migrations.AddField(
            model_name='agenteaduanal',
            name='regimen_fiscal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Core.regimenfiscal', verbose_name='Régimen Fiscal'),
        ),
        migrations.AddField(
            model_name='agenteaduanal',
            name='rfc',
            field=models.CharField(default='XAXX010101000', max_length=20, verbose_name='RFC'),
        ),
        migrations.AddField(
            model_name='agenteaduanal',
            name='tipo_rfc',
            field=models.CharField(blank=True, choices=[('FISICA', 'Persona Física'), ('MORAL', 'Persona Moral'), ('EXTRANJERO', 'Persona Extranjera')], max_length=50, null=True, verbose_name='Tipo RFC'),
        ),
        migrations.AddField(
            model_name='agenteaduanal',
            name='usoCFDI',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Core.usocfdi', verbose_name='Uso CFDI'),
        ),
        migrations.CreateModel(
            name='ContactoAgenteAduanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre')),
                ('movil', models.CharField(blank=True, max_length=20, null=True, verbose_name='Móvil')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('agente_aduanal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contacto_agente_aduanal', to='AgenciamientoAduanal.agenteaduanal', verbose_name='Agente Aduanal')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
