# Generated by Django 5.0.4 on 2025-07-09 18:32

import AgenciamientoAduanal.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgenciamientoAduanal', '0005_remove_agenteaduanal_correo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentosAgenteAduanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constancia_fiscal', models.FileField(upload_to=AgenciamientoAduanal.models.documentos_cliente_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Constancia Fiscal (PDF)')),
                ('agente_aduanal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AgenciamientoAduanal.agenteaduanal', verbose_name='Cliente Padre')),
            ],
        ),
    ]
