# Generated by Django 5.0.4 on 2025-07-10 15:34

import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgenciamientoAduanal', '0006_documentosagenteaduanal'),
        ('Core', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactoAgenteAduanal',
            new_name='ContactoAgenciaAduanal',
        ),
        migrations.RenameModel(
            old_name='DocumentosAgenteAduanal',
            new_name='DocumentosAgenciaAduanal',
        ),
        migrations.RemoveField(
            model_name='agenciaaduanal',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='agenciaaduanal',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='agenteaduanal',
            name='calle',
        ),
        migrations.RemoveField(
            model_name='agenteaduanal',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='agenteaduanal',
            name='codigo_postal',
        ),
        migrations.RemoveField(
            model_name='agenteaduanal',
            name='colonia',
        ),
        migrations.RemoveField(
            model_name='agenteaduanal',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='agenteaduanal',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='agenteaduanal',
            name='localidad',
        ),
        migrations.RemoveField(
            model_name='agenteaduanal',
            name='numero_exterior',
        ),
        migrations.RemoveField(
            model_name='agenteaduanal',
            name='numero_interior',
        ),
        migrations.RemoveField(
            model_name='agenteaduanal',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='agenteaduanal',
            name='razon_social',
        ),
        migrations.RemoveField(
            model_name='agenteaduanal',
            name='referencia',
        ),
        migrations.RemoveField(
            model_name='agenteaduanal',
            name='regimen_fiscal',
        ),
        migrations.RemoveField(
            model_name='agenteaduanal',
            name='rfc',
        ),
        migrations.RemoveField(
            model_name='agenteaduanal',
            name='tipo_rfc',
        ),
        migrations.RemoveField(
            model_name='agenteaduanal',
            name='usoCFDI',
        ),
        migrations.RemoveField(
            model_name='contactoagenciaaduanal',
            name='agente_aduanal',
        ),
        migrations.RemoveField(
            model_name='documentosagenciaaduanal',
            name='agente_aduanal',
        ),
        migrations.AddField(
            model_name='agenciaaduanal',
            name='calle',
            field=models.CharField(default='Sin especificar', max_length=255, verbose_name='Calle'),
        ),
        migrations.AddField(
            model_name='agenciaaduanal',
            name='ciudad',
            field=models.CharField(default='Sin especificar', max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='agenciaaduanal',
            name='codigo_postal',
            field=models.IntegerField(default=0, verbose_name='Código Postal'),
        ),
        migrations.AddField(
            model_name='agenciaaduanal',
            name='colonia',
            field=models.CharField(default='Sin especificar', max_length=100, verbose_name='Colonia'),
        ),
        migrations.AddField(
            model_name='agenciaaduanal',
            name='estado',
            field=models.CharField(default='Sin especificar', max_length=100, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='agenciaaduanal',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación'),
        ),
        migrations.AddField(
            model_name='agenciaaduanal',
            name='localidad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Localidad'),
        ),
        migrations.AddField(
            model_name='agenciaaduanal',
            name='numero_exterior',
            field=models.IntegerField(default=0, verbose_name='Número Exterior'),
        ),
        migrations.AddField(
            model_name='agenciaaduanal',
            name='numero_interior',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número Interior'),
        ),
        migrations.AddField(
            model_name='agenciaaduanal',
            name='pais',
            field=django_countries.fields.CountryField(default='MX', max_length=2),
        ),
        migrations.AddField(
            model_name='agenciaaduanal',
            name='razon_social',
            field=models.CharField(default='Por definir', max_length=255, verbose_name='Razón Social'),
        ),
        migrations.AddField(
            model_name='agenciaaduanal',
            name='referencia',
            field=models.TextField(blank=True, null=True, verbose_name='Referencia'),
        ),
        migrations.AddField(
            model_name='agenciaaduanal',
            name='regimen_fiscal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Core.regimenfiscal', verbose_name='Régimen Fiscal'),
        ),
        migrations.AddField(
            model_name='agenciaaduanal',
            name='rfc',
            field=models.CharField(default='XAXX010101000', max_length=20, verbose_name='RFC'),
        ),
        migrations.AddField(
            model_name='agenciaaduanal',
            name='tipo_rfc',
            field=models.CharField(blank=True, choices=[('FISICA', 'Persona Física'), ('MORAL', 'Persona Moral'), ('EXTRANJERO', 'Persona Extranjera')], max_length=50, null=True, verbose_name='Tipo RFC'),
        ),
        migrations.AddField(
            model_name='agenciaaduanal',
            name='usoCFDI',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Core.usocfdi', verbose_name='Uso CFDI'),
        ),
        migrations.AddField(
            model_name='agenteaduanal',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AddField(
            model_name='agenteaduanal',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre de la Agencia Aduanal'),
        ),
        migrations.AddField(
            model_name='agenteaduanal',
            name='patente',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Patente Aduanal'),
        ),
        migrations.AddField(
            model_name='contactoagenciaaduanal',
            name='agencia_aduanal',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contacto_agente_aduanal', to='AgenciamientoAduanal.agenciaaduanal', verbose_name='Agente Aduanal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentosagenciaaduanal',
            name='agencia_aduanal',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='AgenciamientoAduanal.agenciaaduanal', verbose_name='Cliente Padre'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agenciaaduanal',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_agente_aduanal', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='agenteaduanal',
            name='agencia_aduanal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agentes_aduanales', to='AgenciamientoAduanal.agenciaaduanal', verbose_name='Agencia Aduanal'),
        ),
        migrations.AlterField(
            model_name='agenteaduanal',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_agencia_aduanal', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
