# Generated by Django 5.0.4 on 2025-07-10 15:42

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgenciamientoAduanal', '0008_alter_agenciaaduanal_razon_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenciaaduanal',
            name='pais',
            field=django_countries.fields.CountryField(default='mx', max_length=2),
        ),
        migrations.AlterField(
            model_name='agenciaaduanal',
            name='razon_social',
            field=models.CharField(default='Por definir', max_length=255, verbose_name='Razón Social'),
        ),
    ]
