# Generated by Django 5.0.4 on 2025-07-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgenciamientoAduanal', '0010_alter_agenciaaduanal_pais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenciaaduanal',
            name='calle',
            field=models.CharField(max_length=255, verbose_name='Calle'),
        ),
        migrations.AlterField(
            model_name='agenciaaduanal',
            name='ciudad',
            field=models.CharField(max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='agenciaaduanal',
            name='codigo_postal',
            field=models.IntegerField(verbose_name='Código Postal'),
        ),
        migrations.AlterField(
            model_name='agenciaaduanal',
            name='colonia',
            field=models.CharField(max_length=100, verbose_name='Colonia'),
        ),
        migrations.AlterField(
            model_name='agenciaaduanal',
            name='estado',
            field=models.CharField(max_length=100, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='agenciaaduanal',
            name='razon_social',
            field=models.CharField(max_length=255, verbose_name='Razón Social'),
        ),
        migrations.AlterField(
            model_name='agenciaaduanal',
            name='rfc',
            field=models.CharField(max_length=20, verbose_name='RFC'),
        ),
        migrations.AlterField(
            model_name='agenciaaduanal',
            name='tipo_rfc',
            field=models.CharField(choices=[('FISICA', 'Persona Física'), ('MORAL', 'Persona Moral'), ('EXTRANJERO', 'Persona Extranjera')], default='Persona Moral', max_length=50, verbose_name='Tipo RFC'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactoagenciaaduanal',
            name='movil',
            field=models.CharField(max_length=20, verbose_name='Móvil'),
        ),
        migrations.AlterField(
            model_name='contactoagenciaaduanal',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='contactoagenciaaduanal',
            name='notas',
            field=models.TextField(verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='contactoagenciaaduanal',
            name='telefono',
            field=models.CharField(max_length=20, verbose_name='Teléfono'),
        ),
    ]
