# Generated by Django 5.0.4 on 2025-07-10 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgenciamientoAduanal', '0012_alter_agenciaaduanal_user_alter_agenteaduanal_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactoagenciaaduanal',
            name='agencia_aduanal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contacto_agencia_aduanal', to='AgenciamientoAduanal.agenciaaduanal', verbose_name='Agente Aduanal'),
        ),
    ]
