# Generated by Django 5.0.14 on 2025-06-05 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clientes', '0003_clientehijo_servicios_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoSegregacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('grupo', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_operacion', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('tipo_servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Clientes.tipodeservicio', verbose_name='Tipo de Servicio')),
            ],
        ),
    ]
