# Generated by Django 5.0.14 on 2025-06-05 17:40

import Solicitudes.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0003_clientehijo_servicios_and_more'),
        ('Solicitudes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudMasiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='Pendiente', max_length=50)),
                ('excel', models.FileField(upload_to=Solicitudes.models.documentos_cliente_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx'])], verbose_name='contrato (PDF)')),
                ('cliente_padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.clientepadre', verbose_name='Cliente Padre')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.tipodeservicio', verbose_name='Servicio')),
                ('tipo_segregacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Solicitudes.tiposegregacion', verbose_name='Tipo de Segregación')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudIndividual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=100, unique=True)),
                ('estado', models.CharField(default='Pendiente', max_length=50)),
                ('estatus_n4', models.CharField(default='Pendiente', max_length=50)),
                ('bl', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_tamaño', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cita_masiva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_individuales', to='Solicitudes.solicitudmasiva', verbose_name='Cita Masiva')),
            ],
        ),
    ]
