# Generated by Django 5.0.14 on 2025-06-05 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0003_clientehijo_servicios_and_more'),
        ('Solicitudes', '0002_solicitudmasiva_solicitudindividual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudmasiva',
            name='cliente_padre',
        ),
        migrations.AddField(
            model_name='solicitudmasiva',
            name='cliente_hijo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Clientes.clientehijo', verbose_name='Cliente Hijo'),
            preserve_default=False,
        ),
    ]
