# Generated by Django 5.0.14 on 2025-06-05 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solicitudes', '0003_remove_solicitudmasiva_cliente_padre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudindividual',
            name='folio',
        ),
        migrations.RemoveField(
            model_name='solicitudmasiva',
            name='estado',
        ),
        migrations.AddField(
            model_name='solicitudindividual',
            name='buque',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitudindividual',
            name='contenedor',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitudindividual',
            name='esReefer',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitudindividual',
            name='eta',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitudindividual',
            name='imo',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitudindividual',
            name='isOOG',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitudindividual',
            name='viaje',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitudindividual',
            name='bl',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitudindividual',
            name='estado',
            field=models.CharField(default='Nueva', max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitudindividual',
            name='estatus_n4',
            field=models.CharField(default='Nueva', max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitudindividual',
            name='tipo_tamaño',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tiposegregacion',
            name='grupo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tiposegregacion',
            name='tipo_operacion',
            field=models.CharField(max_length=50),
        ),
    ]
