# Generated by Django 5.0.14 on 2025-06-11 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Solicitudes', '0004_remove_solicitudindividual_folio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitudindividual',
            old_name='cita_masiva',
            new_name='solicitud_masiva',
        ),
    ]
