# Generated by Django 5.0.4 on 2025-06-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solicitudes', '0005_rename_cita_masiva_solicitudindividual_solicitud_masiva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudindividual',
            name='bl',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='solicitudindividual',
            name='buque',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='solicitudindividual',
            name='esReefer',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='solicitudindividual',
            name='eta',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='solicitudindividual',
            name='isOOG',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='solicitudindividual',
            name='tipo_tamaño',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='solicitudindividual',
            name='viaje',
            field=models.CharField(max_length=17),
        ),
    ]
