# Generated by Django 5.0.4 on 2025-06-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solicitudes', '0006_alter_solicitudindividual_bl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudindividual',
            name='buque',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudindividual',
            name='esReefer',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudindividual',
            name='eta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudindividual',
            name='imo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudindividual',
            name='isOOG',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudindividual',
            name='tipo_tamaño',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudindividual',
            name='viaje',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
    ]
