# Generated by Django 5.0.4 on 2025-06-23 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solicitudes', '0007_alter_solicitudindividual_buque_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudindividual',
            name='imo',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
