# Generated by Django 5.0.4 on 2025-06-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solicitudes', '0008_alter_solicitudindividual_imo'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudindividual',
            name='eliminada',
            field=models.BooleanField(default=False),
        ),
    ]
