# Generated by Django 5.0.4 on 2025-06-25 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0006_alter_clientepadre_user'),
        ('Solicitudes', '0009_solicitudindividual_eliminada'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudmasiva',
            name='cliente_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Clientes.clientepadre', verbose_name='Cliente Padre'),
        ),
        migrations.AlterField(
            model_name='solicitudmasiva',
            name='cliente_hijo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Clientes.clientehijo', verbose_name='Cliente Hijo'),
        ),
    ]
