# Generated by Django 5.0.4 on 2025-07-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solicitudes', '0010_solicitudmasiva_cliente_padre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudindividual',
            name='destino',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
