# Generated by Django 5.0.4 on 2025-07-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solicitudes', '0011_solicitudindividual_destino'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudindividual',
            name='id_contenedor',
            field=models.CharField(default=1, max_length=20, unique=True, verbose_name='ID Contenedor'),
            preserve_default=False,
        ),
    ]
