# Generated by Django 5.0.4 on 2025-07-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solicitudes', '0012_solicitudindividual_id_contenedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudindividual',
            name='id_contenedor',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ID Contenedor'),
        ),
    ]
