# Generated by Django 5.0.4 on 2025-07-11 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgenciamientoAduanal', '0013_alter_contactoagenciaaduanal_agencia_aduanal'),
        ('Clientes', '0013_alter_contactoclientepadre_notas'),
        ('Solicitudes', '0013_alter_solicitudindividual_id_contenedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstatusSolicitudMasiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('NUEVA', 'Nueva'), ('AUTORIZADA', 'Autorizada'), ('RECHAZADA', 'Rechazada')], default='Nueva', max_length=15, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_rechazo', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Rechazo')),
                ('fecha_autorizacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Autorización')),
                ('motivo_rechazo', models.TextField(blank=True, null=True, verbose_name='Motivo de Rechazo')),
                ('solicitud_masiva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estatus_solicitudes', to='Solicitudes.solicitudmasiva', verbose_name='Solicitud Masiva')),
            ],
        ),
        migrations.CreateModel(
            name='SoliciudIndividualTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenedor', models.CharField(max_length=11)),
                ('iniciales_equipo', models.CharField(blank=True, max_length=10, null=True)),
                ('numero_equipo', models.CharField(blank=True, max_length=10, null=True)),
                ('digito_control', models.CharField(blank=True, max_length=1, null=True)),
                ('bl', models.CharField(max_length=16)),
                ('peso_bruto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('longitud_equipo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='longitud del equipo en pies')),
                ('sello_1', models.CharField(blank=True, max_length=20, null=True, verbose_name='Sello 1')),
                ('sello_2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Sello 2')),
                ('sello_3', models.CharField(blank=True, max_length=20, null=True, verbose_name='Sello 3')),
                ('sello_4', models.CharField(blank=True, max_length=20, null=True, verbose_name='Sello 4')),
                ('clave_producto_sat', models.CharField(blank=True, max_length=20, null=True, verbose_name='Clave Producto SAT')),
                ('tipo_material', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Material')),
                ('cantidad', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cantidad')),
                ('descripcion_sat', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('peso_neto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Peso Neto')),
                ('terminal_carga', models.CharField(blank=True, max_length=100, null=True, verbose_name='Terminal de Carga')),
                ('terminal_destino', models.CharField(blank=True, max_length=100, null=True, verbose_name='Terminal de Destino')),
                ('numero_pedimento', models.CharField(blank=True, max_length=20, null=True, verbose_name='Pedimento')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('eliminada', models.BooleanField(default=False)),
                ('agente_aduanal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_individuales_transporte_agente_aduanal', to='AgenciamientoAduanal.agenteaduanal', verbose_name='Agente Aduanal')),
                ('cliente_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_individuales_transporte_cliente_padre', to='Clientes.clientepadre', verbose_name='Cliente Padre')),
                ('solicitud_masiva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_individuales_transporte', to='Solicitudes.solicitudmasiva', verbose_name='Cita Masiva')),
            ],
        ),
    ]
