# Generated by Django 5.0.4 on 2025-07-17 18:35

import Solicitudes.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solicitudes', '0014_estatussolicitudmasiva_soliciudindividualtransporte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soliciudindividualtransporte',
            name='agente_aduanal',
        ),
        migrations.RemoveField(
            model_name='soliciudindividualtransporte',
            name='cliente_padre',
        ),
        migrations.RemoveField(
            model_name='soliciudindividualtransporte',
            name='solicitud_masiva',
        ),
        migrations.AlterField(
            model_name='solicitudmasiva',
            name='excel',
            field=models.FileField(upload_to=Solicitudes.models.documentos_cliente_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'csv'])], verbose_name='contrato (PDF)'),
        ),
        migrations.DeleteModel(
            name='EstatusSolicitudMasiva',
        ),
        migrations.DeleteModel(
            name='SoliciudIndividualTransporte',
        ),
    ]
