# Generated by Django 5.0.14 on 2025-05-22 14:45

import Clientes.models
import django.core.validators
import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegimenFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(verbose_name='Código')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDeServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(max_length=100, verbose_name='Servicio')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='TipoEntidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoEntidad', models.CharField(max_length=100, unique=True, verbose_name='Tipo de Entidad')),
            ],
        ),
        migrations.CreateModel(
            name='UsoCFDI',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Código')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='ClientePadre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuarios_hijo', models.IntegerField(blank=True, null=True, verbose_name='Usuarios Hijo')),
                ('rfc', models.CharField(max_length=20, verbose_name='RFC')),
                ('tipo_rfc', models.CharField(blank=True, choices=[('FISICA', 'Persona Física'), ('MORAL', 'Persona Moral'), ('EXTRANJERO', 'Persona Extranjera')], max_length=50, null=True, verbose_name='Tipo RFC')),
                ('razon_social', models.CharField(max_length=255, verbose_name='Razón Social')),
                ('pais', django_countries.fields.CountryField(max_length=2)),
                ('estado', models.CharField(max_length=100, verbose_name='Estado')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('colonia', models.CharField(max_length=100, verbose_name='Colonia')),
                ('localidad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Localidad')),
                ('codigo_postal', models.IntegerField(verbose_name='Código Postal')),
                ('calle', models.CharField(max_length=255, verbose_name='Calle')),
                ('numero_exterior', models.IntegerField(verbose_name='Número Exterior')),
                ('numero_interior', models.IntegerField(blank=True, null=True, verbose_name='Número Interior')),
                ('referencia', models.TextField(blank=True, null=True, verbose_name='Referencia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('regimen_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Clientes.regimenfiscal', verbose_name='Régimen Fiscal')),
                ('servicios', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Clientes.tipodeservicio', verbose_name='servicios')),
                ('tipoEntidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Clientes.tipoentidad', verbose_name='Tipo de Entidad')),
                ('usoCFDI', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Clientes.usocfdi', verbose_name='Uso CFDI')),
            ],
        ),
        migrations.CreateModel(
            name='ClienteHijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('cliente_padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.clientepadre', verbose_name='Cliente Padre')),
            ],
        ),
        migrations.CreateModel(
            name='ContactoClientePadre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre')),
                ('movil', models.CharField(blank=True, max_length=20, null=True, verbose_name='Móvil')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('cliente_padre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Clientes.clientepadre', verbose_name='Cliente Padre')),
            ],
        ),
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constancia_fiscal', models.FileField(upload_to=Clientes.models.documentos_cliente_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Constancia Fiscal (PDF)')),
                ('contrato', models.FileField(upload_to=Clientes.models.documentos_cliente_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='contrato (PDF)')),
                ('cliente_padre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Clientes.clientepadre', verbose_name='Cliente Padre')),
            ],
        ),
    ]
