# Generated by Django 5.0.14 on 2025-05-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientepadre',
            name='servicios',
        ),
        migrations.RemoveField(
            model_name='clientepadre',
            name='tipoEntidad',
        ),
        migrations.AddField(
            model_name='clientepadre',
            name='servicios',
            field=models.ManyToManyField(to='Clientes.tipodeservicio', verbose_name='servicios'),
        ),
        migrations.AddField(
            model_name='clientepadre',
            name='tipoEntidad',
            field=models.ManyToManyField(to='Clientes.tipoentidad', verbose_name='Tipo de Entidad'),
        ),
    ]
