# Generated by Django 5.0.14 on 2025-06-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0003_clientehijo_servicios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientepadre',
            name='digito_verificador',
            field=models.BooleanField(default=True, verbose_name='Digito Verificador'),
        ),
    ]
