# Generated by Django 5.0.14 on 2025-06-09 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0004_clientepadre_digito_verificador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientepadre',
            name='usuarios_hijo',
        ),
    ]
