# Generated by Django 5.0.14 on 2025-06-11 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0005_remove_clientepadre_usuarios_hijo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientepadre',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_padre', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
