# Generated by Django 5.0.4 on 2025-07-08 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0006_alter_clientepadre_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientepadre',
            name='tipoEntidad',
        ),
        migrations.DeleteModel(
            name='TipoEntidad',
        ),
    ]
