# Generated by Django 5.0.4 on 2025-07-09 16:59

import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0007_remove_clientepadre_tipoentidad_delete_tipoentidad'),
        ('Core', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientepadre',
            name='regimen_fiscal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Core.regimenfiscal', verbose_name='Régimen Fiscal'),
        ),
        migrations.AlterField(
            model_name='clientepadre',
            name='usoCFDI',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Core.usocfdi', verbose_name='Uso CFDI'),
        ),
        migrations.RenameField(
            model_name='clientehijo',
            old_name='created_at',
            new_name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='clientepadre',
            name='created_at',
        ),
        migrations.AddField(
            model_name='clientepadre',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='clientepadre',
            name='calle',
            field=models.CharField(default='Sin especificar', max_length=255, verbose_name='Calle'),
        ),
        migrations.AlterField(
            model_name='clientepadre',
            name='ciudad',
            field=models.CharField(default='Sin especificar', max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='clientepadre',
            name='codigo_postal',
            field=models.IntegerField(default=0, verbose_name='Código Postal'),
        ),
        migrations.AlterField(
            model_name='clientepadre',
            name='colonia',
            field=models.CharField(default='Sin especificar', max_length=100, verbose_name='Colonia'),
        ),
        migrations.AlterField(
            model_name='clientepadre',
            name='estado',
            field=models.CharField(default='Sin especificar', max_length=100, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='clientepadre',
            name='numero_exterior',
            field=models.IntegerField(default=0, verbose_name='Número Exterior'),
        ),
        migrations.AlterField(
            model_name='clientepadre',
            name='pais',
            field=django_countries.fields.CountryField(default='Sin especificar', max_length=2),
        ),
        migrations.AlterField(
            model_name='clientepadre',
            name='razon_social',
            field=models.CharField(default='Por definir', max_length=255, verbose_name='Razón Social'),
        ),
        migrations.AlterField(
            model_name='clientepadre',
            name='rfc',
            field=models.CharField(default='XAXX010101000', max_length=20, verbose_name='RFC'),
        ),
        migrations.DeleteModel(
            name='RegimenFiscal',
        ),
        migrations.DeleteModel(
            name='UsoCFDI',
        ),
    ]
