# Generated by Django 5.0.4 on 2025-07-10 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0008_alter_clientepadre_regimen_fiscal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientepadre',
            name='razon_social',
            field=models.CharField(default='Mx', max_length=255, verbose_name='Razón Social'),
        ),
    ]
