# Generated by Django 5.0.4 on 2025-07-10 15:47

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0010_alter_clientepadre_pais_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientepadre',
            name='pais',
            field=django_countries.fields.CountryField(default='MX', max_length=2),
        ),
    ]
