# Generated by Django 5.0.4 on 2025-07-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0011_alter_clientepadre_pais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientepadre',
            name='calle',
            field=models.CharField(max_length=255, verbose_name='Calle'),
        ),
        migrations.AlterField(
            model_name='clientepadre',
            name='ciudad',
            field=models.CharField(max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='clientepadre',
            name='codigo_postal',
            field=models.IntegerField(verbose_name='Código Postal'),
        ),
        migrations.AlterField(
            model_name='clientepadre',
            name='colonia',
            field=models.CharField(max_length=100, verbose_name='Colonia'),
        ),
        migrations.AlterField(
            model_name='clientepadre',
            name='estado',
            field=models.CharField(max_length=100, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='clientepadre',
            name='razon_social',
            field=models.CharField(max_length=255, verbose_name='Razón Social'),
        ),
        migrations.AlterField(
            model_name='clientepadre',
            name='rfc',
            field=models.CharField(max_length=20, verbose_name='RFC'),
        ),
        migrations.AlterField(
            model_name='clientepadre',
            name='tipo_rfc',
            field=models.CharField(choices=[('FISICA', 'Persona Física'), ('MORAL', 'Persona Moral'), ('EXTRANJERO', 'Persona Extranjera')], max_length=50, verbose_name='Tipo RFC'),
        ),
        migrations.AlterField(
            model_name='contactoclientepadre',
            name='movil',
            field=models.CharField(max_length=20, verbose_name='Móvil'),
        ),
        migrations.AlterField(
            model_name='contactoclientepadre',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='contactoclientepadre',
            name='notas',
            field=models.TextField(verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='contactoclientepadre',
            name='telefono',
            field=models.CharField(max_length=20, verbose_name='Teléfono'),
        ),
    ]
