# Generated by Django 5.0.4 on 2025-07-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0012_alter_clientepadre_calle_alter_clientepadre_ciudad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactoclientepadre',
            name='notas',
            field=models.TextField(blank=True, null=True, verbose_name='Notas'),
        ),
    ]
